---
name: Generic build sbt with test coverage and sonar
description: 'Generic build sbt with test coverage and sonar'

inputs:
  sonar_token:
    description: 'Sonar token'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Run tests and build coverage report
      shell: bash
      run: sbt coverage test coverageReport
#    - name: SonarCloud Scan
#      uses: SonarSource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ inputs.github_token }}
#        SONAR_TOKEN: ${{ inputs.sonar_token }}

# https://github.com/marketplace/actions/sonarcloud-scoverage-fix

    - name: SonarCloud scan fixed
      uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.0
      with:
        scoverageReport: target/scala-2.13/scoverage-report/scoverage.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
    - name: Build jar
      shell: bash
      run: sbt clean compile assembly
