version: '3'

services:
  app:
    image: wishlist:latest
    build: .
    networks:
      - backend

  nginx:
    image: wishlist-static:latest
    build: ./static/
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
