version: '3'

services:
  app:
    image: ghcr.io/antonovdmitriy/crud-wishlist-scala-sqlite/wishlist-scala-akka-sqlite:latest
    networks:
      - backend

  nginx:
    image: ghcr.io/antonovdmitriy/crud-wishlist-scala-sqlite/wishlist-front-static:latest
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
