name: On new release

on:
  release:
    types: [created]

jobs:
  build-and-push-image-to-registry:
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Generic build sbt with test coverage and sonar
        uses: ./.github/actions/generic-build-sbt-with-test-coverage-and-sonar/
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create docker release image and push to registry
        uses: ./.github/actions/build-image-and-push-to-registry/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          image_name: wishlist-image