---
name: test compose to ec2

on:
  push:
    branches:
      - '13-docker-compose-file'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SOURCE: "./compose/"
          REMOTE_HOST: ${{ secrets.EC2_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.EC2_REMOTE_USER }}
          TARGET: "/home/ubuntu/wishlist"
          SCRIPT_AFTER: |
            cd /home/ubuntu/wishlist
            docker-compose down
            docker-compose pull
            docker-compose up -d
